### ISSUE TITLE
Add option for line break ('<br>') character

### ISSUE THREAD

**Issue by bert-bruggeman** [ts-stack/markdown#10]
I would like to use a backslash `\` instead of double spaces to render a line break, maybe this could be an option in the settings - or is it possible somehow to change the regex for a line break?

**Comment by KostyaTretyak** [comment]
Have you tried the [br()](https://github.com/ts-stack/markdown#renderer-methods-api) method?

**Comment by KostyaTretyak** [comment]
See also [Overriding renderer methods](https://github.com/ts-stack/markdown#overriding-renderer-methods)

**Comment by bert-bruggeman** [comment]
I don't want to change the renderer but the token/regex in the lexer...

**Comment by KostyaTretyak** [comment]
But you wrote:
> I would like to use a backslash `\` instead of double spaces `to render` a line break

and lexer it is not about render.

**Comment by bert-bruggeman** [comment]
My mistake, english is not my main language...

**Comment by KostyaTretyak** [comment]
OK. If you need `InlineLexer` to change regexp for `br` token, there is currently no easy way to accomplish this.

**Comment by bert-bruggeman** [comment]
I found a temporary dirty solution without forking the module... 

```js
class CustomRenderer extends Renderer {
  paragraph(text) {
    return `<p>${text.replace(/\\/g,'<br>')}</p>`
  }
}
```
