### ISSUE TITLE
gfm code fence info string should allow multipe words

### ISSUE THREAD

**Issue by mvanassche** [ts-stack/markdown#19]
https://github.github.com/gfm/#example-113

```
~~~~    ruby startline=3 $%@#$
def foo(x)
  return 3
end
~~~~~~~
```

As far as I can tell, the regexp 
```
        fences: /^ *(`{3,}|~{3,})[ \.]*(\S+)? *\n([\s\S]*?)\s*\1 *(?:\n+|$)/,
```
does not support that, and thus does not recognizes the code block.

**Comment by KostyaTretyak** [comment]
Done in https://github.com/ts-stack/markdown/pull/20
