### ISSUE TITLE
IE 11 issue on 1.0.0-beta.5

### ISSUE THREAD

**Issue by johnykifle** [ts-stack/markdown#9]
Hello,

The latest versjon of markdown-ts has issue with polyfills. 

Issue is in this line

 https://github.com/ts-stack/markdown/blob/cb5c7ccd3d7f2ac7675eff96f57a608795837872/src/marked.ts#L25

### Describe the bug
The latest version or 1.0.0-beta.5 does not work in IE 11

### To Reproduce
Import it in any file and open this one in IE 11

### Expected behavior
It works :) .

**Comment by KostyaTretyak** [comment]
IE does not supported. Sorry.
